language: python
python:
  - "2.7"

notifications:
    email: false

install:
    - pip install Cython
    - pip install -r requirements.txt

script:
    - python setup.py build_ext --inplace
    - nosetests